theme: jekyll-theme-dinky
title: Jeremy Miller
description: Data Scientist
permalink: pretty
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LearningMap.md
  - posts/toc.md
  - posts/odscwest2021.md
  - posts/inspired.md
